#!/sw/bin/python3.5

# ----------------------------------------------------------------------------------------------- #
# kosudoku-batch
# Created by Buz Barstow 2016-05-06
# ----------------------------------------------------------------------------------------------- #

from kosudoku.input import get_input
from kosudoku.batch import CalculateNPick, CalculateNPoolDays, CalculateNPool
import sys

# ----------------------------------------------------------------------------------------------- #
# Import the input parameter file

inputParameters = ['Nplate', 'tLiquid', 'tSolid', 'tIncubate', 'rPick', 'tRest', 'mutantsPerPlate']

argv = sys.argv

inputParameterValues = get_input(argv, inputParameters)
# ----------------------------------------------------------------------------------------------- #

# ----------------------------------------------------------------------------------------------- #
# Parse the input data
Nplate = float(inputParameterValues['Nplate'])
tLiquid = float(inputParameterValues['tLiquid'])
tSolid = float(inputParameterValues['tSolid'])
tIncubate = float(inputParameterValues['tIncubate'])
rPick = float(inputParameterValues['rPick'])
tRest = float(inputParameterValues['tRest'])
mutantsPerPlate = int(inputParameterValues['mutantsPerPlate'])

# Calculate the number of mutants that we can pick, and the number of days we can do it over
Npick, pickDays, tPickPerDay = CalculateNPick(tLiquid, tSolid, rPick=rPick, tIncubate=tIncubate)


# Calculate the number of days that we can pool over
NPoolDays = CalculateNPoolDays(tLiquid/24, tRest/24, pickDays, tIncubate)

# Calculate the number of mutants that we can pool
Npool = CalculateNPool(60, tLiquid/24, NPoolDays, mutantsPerPlate)

# Calculate the number of mutants in a batch
Nbatch = min([Npool, Nplate, Npick])

print("Maximum number of mutants that can be picked, Npick = " + str(Npick) + " colonies\n")
print("Maximum number of days over which we can pick, pickDays = " + str(pickDays) + " days\n")
print("Picking time per day: " + '{:0.1f}'.format(tPickPerDay) + " hours\n")
print("Maximum number of mutants that can be pooled, Npool = " + str(Npool) + " colonies\n")
print("Number of mutants per batch that can be pooled, Nbatch = " + str(Nbatch) + " colonies\n")

# ----------------------------------------------------------------------------------------------- #
