#!/sw/bin/python3.5

# ----------------------------------------------------------------------------------------------- #
# kosudoku-egeneindex
# Created by Buz Barstow 2016-05-07
#
# Code that uses gene essentiality data to build a lookup table connecting the location
# of each possible transposon insertion site in a genome to a locus and its essentiality. 
# At this point, we expect that the essentiality data and the genome sequence file have been
# conditioned so that there is an essentiality tag for each locus. 
# ----------------------------------------------------------------------------------------------- #

from kosudoku.utils import ensure_dir, FindATandTAPositions
from kosudoku.input import get_input
from kosudoku.feature import ImportFeatureArrayFromGenBank
from kosudoku.montecarlo import ImportEssentialityData

import sys

# ----------------------------------------------------------------------------------------------- #
# Import the input parameter file
inputParameters = [\
'essentialityDataFileName', 'referenceGenomeGenBankFileName', 'outputFileName']

argv = sys.argv
inputParameterValues = get_input(argv, inputParameters)
# ----------------------------------------------------------------------------------------------- #

# ----------------------------------------------------------------------------------------------- #
# Parse the input data
referenceGenomeGenBankFileName = inputParameterValues['referenceGenomeGenBankFileName']
essentialityDataFileName = inputParameterValues['essentialityDataFileName']
outputFileName = inputParameterValues['outputFileName']
# ----------------------------------------------------------------------------------------------- #

# ----------------------------------------------------------------------------------------------- #
ensure_dir(outputFileName)
# ----------------------------------------------------------------------------------------------- #

# ----------------------------------------------------------------------------------------------- #
[ATandTAPositions, sequence] = FindATandTAPositions(referenceGenomeGenBankFileName, \
format='genbank')

essentialityDict = ImportEssentialityData(essentialityDataFileName)
featureArray = ImportFeatureArrayFromGenBank(referenceGenomeGenBankFileName)
# ----------------------------------------------------------------------------------------------- #

# ----------------------------------------------------------------------------------------------- #
# Go through all of the features in the imported genome and extract the ones that refer to genes
geneFeatures = []

for feature in featureArray:
	if feature.featureType == 'gene':
		geneFeatures.append(feature)
# ----------------------------------------------------------------------------------------------- #

# ----------------------------------------------------------------------------------------------- #
# Go through the gene feature array (which is where we have gene coordinate information) and 
# see if we can find a matching locus in the essentiality data. If so, mark the gene with that data,
# if not, mark the gene as unknown which implies non-essential (giving the smallest number of 
# essential genes and the largest number of non-essentials). 

# Makes the assumption that there is only one locus tag per gene

essentialityLocusTags = essentialityDict.keys()

geneLocusDict = {}

for feature in geneFeatures:
	locusTag = feature.tagDict['locus_tag'][0]
	startCoord = feature.startCoord
	endCoord = feature.endCoord
	
	if locusTag in essentialityLocusTags:
		feature.tagDict['Essentiality'] = essentialityDict[locusTag][1]
	else:
		feature.tagDict['Essentiality'] = 'Dispensable'
		
	essentialityTag = feature.tagDict['Essentiality']
		
	geneLocusDict[locusTag] = \
	{'startCoord':startCoord, 'endCoord':endCoord, 'essentialityTag':essentialityTag}

locusKeys = list(geneLocusDict.keys())
# ----------------------------------------------------------------------------------------------- #


# ----------------------------------------------------------------------------------------------- #
# Next, tie the AT and TA positions to gene loci
# Use this stage of the algorithm to calculate what is hittable and what isn't. 

transposonCoordToFeatureDict = {}

i = 0
while i < len(ATandTAPositions):
	
	coord = ATandTAPositions[i]
	
	j = 0
	coordFoundInsideLoci = False
	while j < len(locusKeys):
		key = locusKeys[j]
		startCoord = geneLocusDict[key]['startCoord']
		endCoord = geneLocusDict[key]['endCoord']
		essentiality =  geneLocusDict[key]['essentialityTag']
		
		if (startCoord <= coord <= endCoord):
			transposonCoordToFeatureDict[coord] = [key, essentiality]
			coordFoundInsideLoci = True
		j += 1
	
	if coordFoundInsideLoci == False:
		transposonCoordToFeatureDict[coord] = ['non-coding', 'Dispensable']
	
	i += 1

transposonCoordToFeatureDictFileHandle = open(outputFileName, 'w')

for key in transposonCoordToFeatureDict.keys():
	data = transposonCoordToFeatureDict[key]
	outputStr = str(key) + ',' + str(data[0]) + ',' + str(data[1]) + '\n'
	transposonCoordToFeatureDictFileHandle.write(outputStr)

transposonCoordToFeatureDictFileHandle.close()
# ----------------------------------------------------------------------------------------------- #
